### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [hyunjun/bookmarks#2]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`app.md`](https://github.com/hyunjun/bookmarks/blob/5bf7ba7e63c5f6c7fa869812a41d25cf9454a75b/app.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by hyunjun** [comment]
@reitermarkus I didn't know that you give me an issue. Thanks for coming here and I modified it even if I am very late :)
