### ISSUE TITLE
Jsp programming in netbeans

### ISSUE THREAD

**Issue by saisamba** [hyunjun/bookmarks#3]
Is it possible to create a master page in jsp java programming like asp.net... can u please help me how can we do that i trying but not getting the output.. please help me

**Comment by hyunjun** [comment]
@saisamba I didn't do JSP, so don't know yet exactly but you can create a webpage whatever language you use. For example, I googled and found this https://www.srccodes.com/jsp-hello-world-program-using-eclipse-ide-and-tomcat-web-server/
